lc_elev_reclass_esa = [
    {
        "label": "No Data",
        "include_class": 0,
        "lc_value": 0,
        "elev_zone1": 0,
        "elev_zone2": 0,
        "elev_zone3": 0,
        "elev_zone4": 0,
        "include_height": 0,
    },
    {
        "label": "Cropland, rainfed",
        "include_class": 1,
        "lc_value": 10,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Herbaceous cover",
        "lc_value": 11,
        "include_class": 1,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree or shrub cover",
        "lc_value": 12,
        "include_class": 1,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Cropland, irrigated or post‐flooding",
        "include_class": 1,
        "lc_value": 20,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Mosaic cropland (>50%) / natural vegetation (tree, shrub, herbaceous cover) (<50%)",
        "include_class": 1,
        "lc_value": 30,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Mosaic natural vegetation (tree, shrub, herbaceous cover) (>50%) / cropland (<50%)",
        "include_class": 1,
        "lc_value": 40,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, broadleaved, evergreen, closed to open (>15%)",
        "include_class": 1,
        "lc_value": 50,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, broadleaved, deciduous, closed to open (>15%)",
        "include_class": 1,
        "lc_value": 60,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, broadleaved, deciduous, closed (>40%)",
        "include_class": 1,
        "lc_value": 61,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, broadleaved, deciduous, open (15‐40%)",
        "include_class": 1,
        "lc_value": 62,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, evergreen, closed to open (>15%)",
        "include_class": 1,
        "lc_value": 70,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, evergreen, closed (>40%)",
        "include_class": 1,
        "lc_value": 71,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, evergreen, open (15‐40%)",
        "include_class": 1,
        "lc_value": 72,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, deciduous, closed to open (>15%)",
        "include_class": 1,
        "lc_value": 80,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, deciduous, closed (>40%)",
        "include_class": 1,
        "lc_value": 81,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, needleleaved, deciduous, open (15‐40%)",
        "include_class": 1,
        "lc_value": 82,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, mixed leaf type (broadleaved and needleleaved)",
        "include_class": 1,
        "lc_value": 90,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Mosaic tree and shrub (>50%) / herbaceous cover (<50%)",
        "include_class": 1,
        "lc_value": 100,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Mosaic herbaceous cover (>50%) / tree and shrub (<50%)",
        "include_class": 1,
        "lc_value": 110,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Shrubland",
        "include_class": 1,
        "lc_value": 120,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Evergreen shrubland",
        "include_class": 1,
        "lc_value": 121,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Deciduous shrubland",
        "include_class": 1,
        "lc_value": 122,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Grassland",
        "include_class": 1,
        "lc_value": 130,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Lichens and mosses",
        "include_class": 0,
        "lc_value": 140,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Sparse vegetation (tree, shrub, herbaceous cover) (<15%)",
        "include_class": 0,
        "lc_value": 150,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Sparse tree (<15%)",
        "include_class": 1,
        "lc_value": 151,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Sparse shrub (<15%)",
        "include_class": 1,
        "lc_value": 152,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Sparse herbaceous cover (<15%)",
        "include_class": 0,
        "lc_value": 153,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Tree cover, flooded, fresh or brakish water",
        "include_class": 1,
        "lc_value": 160,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Tree cover, flooded, saline water",
        "include_class": 1,
        "lc_value": 170,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Shrub or herbaceous cover, flooded, fresh/saline/brakish water",
        "include_class": 1,
        "lc_value": 180,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 1,
    },
    {
        "label": "Urban areas",
        "include_class": 0,
        "lc_value": 190,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Bare areas",
        "include_class": 0,
        "lc_value": 200,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Consolidated bare areas",
        "include_class": 0,
        "lc_value": 201,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Unconsolidated bare areas",
        "include_class": 0,
        "lc_value": 202,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Water bodies",
        "include_class": 0,
        "lc_value": 210,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
    {
        "label": "Permanent snow and ice",
        "include_class": 0,
        "lc_value": 220,
        "elev_zone1": 3350,
        "elev_zone2": 3350,
        "elev_zone3": 1000,
        "elev_zone4": 3350,
        "include_height": 0,
    },
]
